version: '3.8' # or your desired docker-compose version

services:
  postgres:
    image: postgres:latest # or a specific version like postgres:14
    environment:
      POSTGRES_USER: myuser # Replace with your desired username
      POSTGRES_PASSWORD: mypassword # Replace with your desired password
      POSTGRES_DB: tictactoe # Replace with your desired database name
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persists data

volumes:
  postgres-data: # Define the volume